/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    BaseSide: typeof import('./src/components/BaseSide.vue')['default']
    ConditionalBranch: typeof import('./src/components/nodes/ConditionalBranch.vue')['default']
    ConditionalBranchDrawer: typeof import('./src/components/nodes/drawer/ConditionalBranchDrawer.vue')['default']
    Database: typeof import('./src/components/nodes/Database.vue')['default']
    DatabaseDrawer: typeof import('./src/components/nodes/drawer/DatabaseDrawer.vue')['default']
    DropzoneBackground: typeof import('./src/components/DropzoneBackground.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FlowDrawer: typeof import('./src/components/FlowDrawer.vue')['default']
    FlowSide: typeof import('./src/components/FlowSide.vue')['default']
    ForEach: typeof import('./src/components/nodes/ForEach.vue')['default']
    ForEachDrawer: typeof import('./src/components/nodes/drawer/ForEachDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Soap: typeof import('./src/components/nodes/Soap.vue')['default']
    WebService: typeof import('./src/components/nodes/WebService.vue')['default']
    WebServiceDrawer: typeof import('./src/components/nodes/drawer/WebServiceDrawer.vue')['default']
  }
}
